<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputadd-to-wishlist-button-14</name>
   <tag></tag>
   <elementGuidId>1dbf4421-3147-4617-baca-406347f34b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='add-to-wishlist-button-14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#add-to-wishlist-button-14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de2e9126-2ab8-4579-a3c8-77f0818c4989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>56bcb61b-1b46-456e-b6a4-fdf821ab4cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-to-wishlist-button-14</value>
      <webElementGuid>a8d1e2c1-d7e7-4395-bbc9-c01c2469c43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-2 add-to-wishlist-button</value>
      <webElementGuid>0c4d8def-8531-406e-9c5b-daa545c03079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add to wishlist</value>
      <webElementGuid>441ad50a-3bfe-4063-99cd-9be482067578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-productid</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>e9d697e2-da92-4552-955e-16f72c5bf4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AjaxCart.addproducttocart_details('/addproducttocart/details/14/2', '#product-details-form');return false;</value>
      <webElementGuid>fe5e9942-1d95-471f-a1dd-ec246f13e55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-wishlist-button-14&quot;)</value>
      <webElementGuid>824eb2ad-7ab8-4cb9-bfb5-35f735903015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='add-to-wishlist-button-14']</value>
      <webElementGuid>8e193fcf-072c-4a98-affb-3e095664d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product-details-form']/div/div/div[2]/div[7]/div/input[3]</value>
      <webElementGuid>81f4bba4-6433-4948-9de4-0fbc9cc58efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>516190b5-73e3-445d-b992-a4c8649167a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'add-to-wishlist-button-14']</value>
      <webElementGuid>c4160544-d7a6-4fb1-883e-0b7fbdbdefea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
